### ISSUE TITLE
Presentación

### ISSUE THREAD

**Issue by josueMerino** [mmasias/idsw2#10]
Tengo una consulta acerca de la presentación, ¿tendríamos que exponer en un powerpoint el modelo de dominio y luego mostrar el código o nos lo dejas a nuestra libertad la forma de presentar? Es decir, el orden obviamente lo escogeríamos nosotros, pero tenía la duda en la forma en la que quieres la presentación

**Comment by mmasias** [comment]
Josué

Como una expo en una reunión de trabajo: optimizando el tiempo vemos modelo del dominio, validamos y luego -si toca- pasamos al código.
