### ISSUE TITLE
Conexión entre atributos y clases

### ISSUE THREAD

**Issue by josueMerino** [mmasias/idsw2#34]
Hola, estoy teniendo problemas con el diagrama de clases, mi problema es que no sé en donde poner los elementos de las celdas, es decir, el gato, la aspiradora, los muebles y las sillas.

Este es mi código en plantUML
```
@startuml
class Edificio {
    - Habitacion habitacion
    - Aspiradora aspiradora
    + limpiarEdificio(Habitacion habitacion, Aspiradora aspiradora)
    + main()
}

class Habitacion{
    - Celda[][] suelo
    - Gato gato
    - Mueble[] muebles
    - Silla[] sillas
    + {static} mostrarHabitacion(Celda[][] suelo)
    + actualizarHabitacion(Celda[][] suelo)
}
class Celda {
    - int posX
    - int posY
    - String representacion
    + getPosX()
    + setPosX(int posX)
    + getPosY()
    + setPosY(int posY)
    + getRepresentacion()
    + setRepresentacion(String representacion)
}
class Aspiradora
class Suciedad
class Batería
class Gato
class Bolsa
class Objeto
class Mueble
class Silla

Habitacion *--> Celda : contiene

Celda o--> Aspiradora 
Celda o--> Gato 
Celda o..> Suciedad
Celda o--> Objeto

Aspiradora o--> Suciedad : elimina
Aspiradora *--> Bolsa : tiene
Aspiradora *--> Batería : tiene

Gato o..> Suciedad : produce

Objeto <|-- Mueble
Objeto <|-- Silla

@enduml
```
También adjuunto el cómo se ve ¿alguna sugerencia o correción?
![image](https://user-images.githubusercontent.com/60791792/159926427-db223725-2b41-48a2-a258-c71c7dbb9d2c.png)

**Comment by mmasias** [comment]
¿Qué opinas de esto?
![](https://www.plantuml.com/plantuml/png/SoWkIImgAStDuN9DoKpBJCxCLz3IrTMrK_18JCeiIGJoyxWGJAYSOt51Pb5YIdvHeeALWdD-NabcQbugfZBdr9mK_2hS4qloaHKW6QodfuSmmRMuvF12Bf1gRE8GNZxOHD_Iz29qSw2YLb1tmyn1Y0SKvQUK9gToSJcavgK0mm80)

**Comment by josueMerino** [comment]
He modificado el modelo de dominio, pero lo veo demasiado engorroso, he tratado de organizarlo, pero no sé si se puede entender

![image](https://user-images.githubusercontent.com/60791792/160272701-c9a91174-0f29-4337-aad0-ff35037dcdad.png)
