### ISSUE TITLE
Horda de Vampiresas

### ISSUE THREAD

**Issue by MarcoGomezGutierrez** [mmasias/idsw2#47]
Hola.

Teníamos una duda, la horda de vampiresas ¿es un modo que el usuario escoge? o ¿es una probabilidad de que pase al crear la partida?

Un saludo.

**Comment by mmasias** [comment]
Al ser una extensión del juego original, tiene más sentido con la elección de una dificultad: modo fácil, una vampiresa, modo difícil, horda de vampiresas.

**Comment by MarcoGomezGutierrez** [comment]
Perfecto.
