### ISSUE TITLE
Documentación con diferentes lenguajes

### ISSUE THREAD

**Issue by josueMerino** [mmasias/idsw2#9]
Tengo una consulta, cuando vayamos a hacer el modelo de dominio ¿podemos usar alternativas a PlantUML o PlainText? Por ejemplo ¿draw.io?

De ser así, que se pueda usar otra alternativa, deberíamos solamente usar esa herramienta para documentación o ¿podríamos variar? Me refiero a que si por ejemplo hago el modelo de dominio en PlantUML, pero quiero explicarlo más a fondo en diagrama de estado en draw.io ¿se permitiría?

**Comment by mmasias** [comment]
Sin problema: pueden usar el lenguaje que como equipo les venga mejor, siempre que quede todo claro.

**Comment by mmasias** [comment]
> _Sin problema: pueden usar el lenguaje que como equipo les venga mejor, siempre que quede todo claro._

Cuando digo ***lenguaje*** me refiero a la herramienta de modelado/documentación
